### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by hummelm10** [p3nt4/Nuages#6]
Can you add a license such as the MIT license to the project? I'd like to fork this and develop on it but potentially release it in the future as a separate project with changes (with credit to you as the original inspiration and base code).

**Comment by p3nt4** [comment]
Havent decided what Licence I would put yet but will add one soon.

Why not just contributing to this repo?

**Comment by hummelm10** [comment]
With work I can't, I was hoping to develop it internally for my team.

**Comment by p3nt4** [comment]
The idea is that handlers/implants are meant to be kept in house so that's not a problem.
Were you planning on working on backend/client components as well? For these, I think it would be great if people could contribute to a centralized project. And if handlers/implants are kept private it shouldn't impact their likelihood of detection.

**Comment by p3nt4** [comment]
Licence added
